<a href="https://colab.research.google.com/github/hoin1357/2023-A-DA/blob/main/week03_seoul_temperature_hskang_ipynb%EC%9D%98_%EC%82%AC%EB%B3%B8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 서울 기온 분석

In [ ]:
import site

In [ ]:
site.getsitepackages()

NameError: name 'site' is not defined

##cvs파일읽기

In [ ]:
import csv

#f=open('seoul csv','r',encoding='cp949')
f=open('seoul.csv')
data=csv.reader(f)

print(data)
f.close()

FileNotFoundError: ignored

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
pwd

'C:\\2023-A-DA'

In [ ]:
import csv

f=open('seoul.scv'.'r'.encoding'cp949')

data=csv.reader(f)

for row in data:
    print(row)

f.close()

['날짜', '지점', '평균기온(℃)', '최저기온(℃)', '최고기온(℃)']
['\t2023-08-21', '108', '29.5', '26', '33.6']
['\t2023-08-22', '108', '27.6', '25.8', '32.2']
['\t2023-08-23', '108', '24.8', '23.2', '27.2']
['\t2023-08-24', '108', '25.1', '22.3', '27.8']
['\t2023-08-25', '108', '26.5', '24', '30']
['\t2023-08-26', '108', '26.4', '23.3', '30.3']
['\t2023-08-27', '108', '26.1', '22.7', '29.6']
['\t2023-08-28', '108', '22.7', '20.8', '25.6']
['\t2023-08-29', '108', '23.9', '22.5', '25.5']
['\t2023-08-30', '108', '22.8', '21.5', '24.5']
['\t2023-08-31', '108', '23.9', '21', '28.9']
['\t2023-09-01', '108', '24.5', '19.7', '29.6']
['\t2023-09-02', '108', '25.4', '19.7', '30.8']
['\t2023-09-03', '108', '25.8', '23.1', '28.8']
['\t2023-09-04', '108', '27', '24.3', '30.2']
['\t2023-09-05', '108', '28.5', '25', '32.8']
['\t2023-09-06', '108', '27.9', '24', '32.1']
['\t2023-09-07', '108', '26.3', '20.9', '31.6']
['\t2023-09-08', '108', '25.3', '19.6', '30.5']
['\t2023-09-09', '108', '25.8', '20.8', '31.2']
['\t2023-09-10', '108', '25.7', '22', '29.6']
['\t2023-09-11', '108', '25.5', '23.1', '29.8']
['\t2023-09-12', '108', '25.7', '21.7', '29.8']
['\t2023-09-13', '108', '22.1', '19.6', '24.6']
['\t2023-09-14', '108', '23.4', '19.2', '27.2']
['\t2023-09-15', '108', '22.3', '20.3', '24.3']
['\t2023-09-16', '108', '23.9', '22', '26.6']
['\t2023-09-17', '108', '24.7', '22', '28']
['\t2023-09-18', '108', '24.7', '22.1', '28.9']
['\t2023-09-19', '108', '24.1', '21.6', '27.2']
['', '', '', '', '']
['', '', '', '', '']
['', '', '', '', '']
['', '', '', '', '']
['', '', '', '', '']
['', '', '', '', '']
['', '', '', '', '']
['\t', '', '', '', '']

In [ ]:
import csv

with open('seoul.csv','r',encoding='cp949') as f:
    data=csv.reader(f)
    for row in data:
        print(row)

['날짜', '지점', '평균기온(℃)', '최저기온(℃)', '최고기온(℃)']
['\t2023-08-21', '108', '29.5', '26', '33.6']
['\t2023-08-22', '108', '27.6', '25.8', '32.2']
['\t2023-08-23', '108', '24.8', '23.2', '27.2']
['\t2023-08-24', '108', '25.1', '22.3', '27.8']
['\t2023-08-25', '108', '26.5', '24', '30']
['\t2023-08-26', '108', '26.4', '23.3', '30.3']
['\t2023-08-27', '108', '26.1', '22.7', '29.6']
['\t2023-08-28', '108', '22.7', '20.8', '25.6']
['\t2023-08-29', '108', '23.9', '22.5', '25.5']
['\t2023-08-30', '108', '22.8', '21.5', '24.5']
['\t2023-08-31', '108', '23.9', '21', '28.9']
['\t2023-09-01', '108', '24.5', '19.7', '29.6']
['\t2023-09-02', '108', '25.4', '19.7', '30.8']
['\t2023-09-03', '108', '25.8', '23.1', '28.8']
['\t2023-09-04', '108', '27', '24.3', '30.2']
['\t2023-09-05', '108', '28.5', '25', '32.8']
['\t2023-09-06', '108', '27.9', '24', '32.1']
['\t2023-09-07', '108', '26.3', '20.9', '31.6']
['\t2023-09-08', '108', '25.3', '19.6', '30.5']
['\t2023-09-09', '108', '25.8', '20.8', '31.2']
['\t2023-09-10', '108', '25.7', '22', '29.6']
['\t2023-09-11', '108', '25.5', '23.1', '29.8']
['\t2023-09-12', '108', '25.7', '21.7', '29.8']
['\t2023-09-13', '108', '22.1', '19.6', '24.6']
['\t2023-09-14', '108', '23.4', '19.2', '27.2']
['\t2023-09-15', '108', '22.3', '20.3', '24.3']
['\t2023-09-16', '108', '23.9', '22', '26.6']
['\t2023-09-17', '108', '24.7', '22', '28']
['\t2023-09-18', '108', '24.7', '22.1', '28.9']
['\t2023-09-19', '108', '24.1', '21.6', '27.2']
['', '', '', '', '']
['', '', '', '', '']
['', '', '', '', '']
['', '', '', '', '']
['', '', '', '', '']
['', '', '', '', '']
['', '', '', '', '']
['\t', '', '', '', '']

In [ ]:
import csv

f=open('seoul.csv','r',encoding='cp949')

data=csv.reader(f)

for row in data:
    if '' in row:
        print(row)

f.close()

['', '', '', '', '']
['', '', '', '', '']
['', '', '', '', '']
['', '', '', '', '']
['', '', '', '', '']
['', '', '', '', '']
['', '', '', '', '']
['\t', '', '', '', '']

import csv

f=open('seoul.csv','r',encoding='cp949')

data=csv.reader(f)

header=next(data)
print(header)

f.close()

In [ ]:
import csv

f=open('seoul.csv','r',encoding='cp949')

data=csv.reader(f)

header=next(data)
print(header)

for row in data:
    print(row)

f.close()

['날짜', '지점', '평균기온(℃)', '최저기온(℃)', '최고기온(℃)']
['\t2023-08-21', '108', '29.5', '26', '33.6']
['\t2023-08-22', '108', '27.6', '25.8', '32.2']
['\t2023-08-23', '108', '24.8', '23.2', '27.2']
['\t2023-08-24', '108', '25.1', '22.3', '27.8']
['\t2023-08-25', '108', '26.5', '24', '30']
['\t2023-08-26', '108', '26.4', '23.3', '30.3']
['\t2023-08-27', '108', '26.1', '22.7', '29.6']
['\t2023-08-28', '108', '22.7', '20.8', '25.6']
['\t2023-08-29', '108', '23.9', '22.5', '25.5']
['\t2023-08-30', '108', '22.8', '21.5', '24.5']
['\t2023-08-31', '108', '23.9', '21', '28.9']
['\t2023-09-01', '108', '24.5', '19.7', '29.6']
['\t2023-09-02', '108', '25.4', '19.7', '30.8']
['\t2023-09-03', '108', '25.8', '23.1', '28.8']
['\t2023-09-04', '108', '27', '24.3', '30.2']
['\t2023-09-05', '108', '28.5', '25', '32.8']
['\t2023-09-06', '108', '27.9', '24', '32.1']
['\t2023-09-07', '108', '26.3', '20.9', '31.6']
['\t2023-09-08', '108', '25.3', '19.6', '30.5']
['\t2023-09-09', '108', '25.8', '20.8', '31.2']
['\t2023-09-10', '108', '25.7', '22', '29.6']
['\t2023-09-11', '108', '25.5', '23.1', '29.8']
['\t2023-09-12', '108', '25.7', '21.7', '29.8']
['\t2023-09-13', '108', '22.1', '19.6', '24.6']
['\t2023-09-14', '108', '23.4', '19.2', '27.2']
['\t2023-09-15', '108', '22.3', '20.3', '24.3']
['\t2023-09-16', '108', '23.9', '22', '26.6']
['\t2023-09-17', '108', '24.7', '22', '28']
['\t2023-09-18', '108', '24.7', '22.1', '28.9']
['\t2023-09-19', '108', '24.1', '21.6', '27.2']
['', '', '', '', '']
['', '', '', '', '']
['', '', '', '', '']
['', '', '', '', '']
['', '', '', '', '']
['', '', '', '', '']
['', '', '', '', '']
['\t', '', '', '', '']

In [ ]:
import csv

f=open('seoul.csv','r',encoding='cp949')
data=csv.reader(f)
header=next(data)

print(header)
for row in data:
    if row[4]=='':
        row[4]=-999

    row[4]=float(row[4])
    print(row)

f.close()

['날짜', '지점', '평균기온(℃)', '최저기온(℃)', '최고기온(℃)']
['\t2023-08-21', '108', '29.5', '26', 33.6]
['\t2023-08-22', '108', '27.6', '25.8', 32.2]
['\t2023-08-23', '108', '24.8', '23.2', 27.2]
['\t2023-08-24', '108', '25.1', '22.3', 27.8]
['\t2023-08-25', '108', '26.5', '24', 30.0]
['\t2023-08-26', '108', '26.4', '23.3', 30.3]
['\t2023-08-27', '108', '26.1', '22.7', 29.6]
['\t2023-08-28', '108', '22.7', '20.8', 25.6]
['\t2023-08-29', '108', '23.9', '22.5', 25.5]
['\t2023-08-30', '108', '22.8', '21.5', 24.5]
['\t2023-08-31', '108', '23.9', '21', 28.9]
['\t2023-09-01', '108', '24.5', '19.7', 29.6]
['\t2023-09-02', '108', '25.4', '19.7', 30.8]
['\t2023-09-03', '108', '25.8', '23.1', 28.8]
['\t2023-09-04', '108', '27', '24.3', 30.2]
['\t2023-09-05', '108', '28.5', '25', 32.8]
['\t2023-09-06', '108', '27.9', '24', 32.1]
['\t2023-09-07', '108', '26.3', '20.9', 31.6]
['\t2023-09-08', '108', '25.3', '19.6', 30.5]
['\t2023-09-09', '108', '25.8', '20.8', 31.2]
['\t2023-09-10', '108', '25.7', '22', 29.6]
['\t2023-09-11', '108', '25.5', '23.1', 29.8]
['\t2023-09-12', '108', '25.7', '21.7', 29.8]
['\t2023-09-13', '108', '22.1', '19.6', 24.6]
['\t2023-09-14', '108', '23.4', '19.2', 27.2]
['\t2023-09-15', '108', '22.3', '20.3', 24.3]
['\t2023-09-16', '108', '23.9', '22', 26.6]
['\t2023-09-17', '108', '24.7', '22', 28.0]
['\t2023-09-18', '108', '24.7', '22.1', 28.9]
['\t2023-09-19', '108', '24.1', '21.6', 27.2]
['', '', '', '', -999.0]
['', '', '', '', -999.0]
['', '', '', '', -999.0]
['', '', '', '', -999.0]
['', '', '', '', -999.0]
['', '', '', '', -999.0]
['', '', '', '', -999.0]
['\t', '', '', '', -999.0]

In [ ]:
import csv

max_temp=-999
max_date=''

f=open('seoul.csv','r',encoding='cp949')
data=csv.reader(f)
header=next(data)

print(header)
for row in data:
    if row[4]=='':
        row[4]=-999

    row[4]=float(row[4])

    if max_temp<row[4]:
        max_temp=row[4]
        max_date=row[0].strip()

f.close()

print(f'관측  이래 서울의 최고기온을 가졌던 날은{max_date}로{max_temp}였습니다.')

['날짜', '지점', '평균기온(℃)', '최저기온(℃)', '최고기온(℃)']
관측  이래 서울의 최고기온을 가졌던 날은2023-08-21로33.6였습니다.